---
- name: "install apache2"
  become: false 
  apt:
    name: ["apache2"]
    state: latest
    update_cache: yes

- name: "install index page"
  become: false
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes


