---
- name: "update apt packages"
  become: true
  #  become method: sudo
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

