---
- name: "update apt packages"
  become: false
  #  become method: sudo
  apt:
    update_cache: yes

- name: "remove dependencies that are no longer required"
  become: false
  apt:
    autoremove: yes

